arm_with_torso:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  
  voxel_resolution: 0.05
  voxel_num_samples: 40 # 40, 272


  x_min: -0.65
  y_min: -1.15
  z_min: -0.25
  x_max:  1.15
  y_max:  1.15
  z_max:  1.95

  display_reachability:
    plane: "YZ+"
    plane_dist: 0.0