left_arm:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  
  voxel_resolution: 0.05
  voxel_num_samples: 32


  x_min: -0.65
  y_min: -0.65
  z_min: -0.35
  x_max:  0.85
  y_max:  0.85
  z_max:  1.25


right_arm:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  
  voxel_resolution: 0.05
  voxel_num_samples: 32


  x_min: -0.65
  y_min: -0.85
  z_min: -0.35
  x_max:  0.85
  y_max:  0.65
  z_max:  1.25