arm:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  ik_type: "manip1"
  ik_start_configs: ["pose_right_0_down", 
                     "pose_right_0_up", 
                     "pose_left_0_down",  
                     "pose_left_0_up"]

  voxel_resolution: 0.05
  voxel_num_samples: 40 # 40, 272


  x_min: 0.0
  y_min: -1.8
  z_min: -1.2
  x_max:  3.4
  y_max:  2.7
  z_max:  2.9

  display_reachability:
    plane: "XY+"
    plane_dist: 0.5

  estimate_reachability:
    max_radius: 4.0
    resolution: 0.10