<?xml version="1.0"?>
<package format="3">
  <name>reachability_applications</name> 
  <version>1.0.0</version>
  <description>
    Tool to test reachability usefulness and simulate robot motion
  </description>
  <author>Ana C. Huaman Quispe</author>
  <maintainer email="mecanita@gmail.com">Ana C. Huaman Quispe</maintainer>

  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>

  <depend>eigen</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_eigen_kdl</depend>
  <depend>tf2_kdl</depend>
  <depend>kdl_parser</depend>
  <depend>trac_ik_lib</depend>
  <depend>urdf</depend>
  <depend>srdfdom</depend>
  <depend>pkg-config</depend>
  <depend>robot_sim_msgs</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>reachability_msgs</depend>
  <depend>reachability_description</depend>
  <depend>rach_ik</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>
