arm_base:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  ik_type: "manip1"
  ik_start_configs: ["left_0_mid", 
                     "left_1_mid", 
                     "left_0_up", 
                     "left_1_up", 
                     "right_0_mid", 
                     "right_1_mid",
                     "right_0_up", 
                     "right_1_up"]

  voxel_resolution: 0.05
  voxel_num_samples: 40 # 40, 272


  x_min: -0.60
  y_min: -0.9
  z_min: -0.1
  x_max:  1.3
  y_max:  0.9
  z_max:  1.7

  display_reachability:
    plane: "XZ+"
    plane_dist: -0.20

  estimate_reachability:
    max_radius: 3.0
    resolution: 0.10    
