panda_manipulator:

  ik_max_time: 0.001
  ik_epsilon: 0.00001
  
  voxel_resolution: 0.05
  voxel_num_samples: 272 # 40 272


  x_min: -0.95
  y_min: -0.95
  z_min: -0.45
  x_max:  0.95
  y_max:  0.95
  z_max:  1.35